# Generated by Django 4.0 on 2021-12-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spelling',
            name='payer',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
