# Generated by Django 4.0 on 2021-12-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spending', '0002_alter_spelling_payer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spelling',
            new_name='Spending',
        ),
    ]
